version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 127.0.0.1:3000:8080
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
