version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 127.0.0.1:3000:8080
    environment:
      SWAGGER_JSON: /api/openapi.yaml
    volumes:
      - ./api-document.yaml:/api/api-document.yaml:ro
