openapi: 3.0.0
info:
  title: "Kanji Numbers Transfer API"
  description: |-
    <b>Kanji Numbers Transfer API仕様</b><br>
    アラビア数字=>漢数字、漢数字=>アラビア数字への変換を行うAPI:
    1. number2kanji: アラビア数字=>漢数字に変換。
       - 1, 2, 3, 10については、それぞれ大字である「壱」「弐」「参」「拾」に変換する。
       - 拾、百、千、万、億、兆それぞれの位が 1 のとき、1 を省略しない ( 1000 =>「壱千」)。
       - 取り扱い可能な数字の範囲は、0 以上、9999 兆 9999 億 9999 万 9999 以下の整数値とする。
    
    2. 漢数字=>アラビア数字に変換。
       - 取り扱い可能な漢数字の範囲は、「零」から「九千九百九拾九兆九千九百九拾九億九千九百九拾九万九千九百九拾九」までとする。
  version: "1.0.0"
servers:
  - url: http://localhost:8080
paths:
  /v1/number2kanji/{アラビア数字}:
    get:
      tags:
      - "number2kanji"
      parameters:
      - name: "アラビア数字"
        in: "path"
        description: "変換元のアラビア数字"
        required: true
        schema:
          type: "integer"
          example: "Ex) 123456789"
      responses:
        "200":
          description: "A successful response."
          content:
            apppplication/json:
              schema:
                type: "string"
                example: "壱億弐千参百四拾五万六千七百八拾九"
        "204":
          description: "A failed response to invalid parameter."
  /v1/kanji2number/{漢数字}:
    get:
      tags:
      - "kanji2number"
      parameters:
      - name: "漢数字"
        in: "path"
        description: "変換元の漢数字"
        required: true
        schema:
          type: "string"
          example: "Ex) 壱億弐千参百四拾五万六千七百八拾九"
      responses:
        "200":
          description: "A successful response."
          content:
            apppplication/json:
              schema:
                type: "string"
                example: "123456789"
        "204":
          description: "A failed response to invalid parameter."
